import React from 'react';
import QRCode from 'react-qr-code';
import { X, Printer } from 'lucide-react';
import { Product } from '../../types';

interface QRModalProps {
  product: Product;
  onClose: () => void;
}

const QRModal: React.FC<QRModalProps> = ({ product, onClose }) => {
  const handlePrint = () => {
    const printWindow = window.open('', '', 'height=500,width=500');
    if (printWindow) {
        // We get the SVG generated by the library
        const svg = document.getElementById("qr-code-svg")?.outerHTML || "";
        
        printWindow.document.write(`
            <html>
                <body style="display:flex; flex-direction:column; align-items:center; justify-content:center; height:100%; font-family:sans-serif;">
                    <h2 style="margin-bottom:10px;">${product.name}</h2>
                    ${svg}
                    <p style="margin-top:10px; font-weight:bold; font-family:monospace;">${product.id}</p>
                    <script>
                        setTimeout(() => { window.print(); window.close(); }, 500);
                    </script>
                </body>
            </html>
        `);
        printWindow.document.close();
    }
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-fade-in">
      <div className="bg-white w-full max-w-sm rounded-2xl p-6 shadow-2xl relative">
        <button onClick={onClose} className="absolute top-4 right-4 text-slate-400 hover:text-slate-600">
          <X size={24} />
        </button>
        
        <h3 className="text-xl font-bold text-slate-800 mb-6 text-center">Etiqueta</h3>
        
        <div className="bg-slate-50 border-2 border-dashed border-slate-200 rounded-xl p-6 flex flex-col items-center">
            <h4 className="font-bold text-lg mb-4 text-center">{product.name}</h4>
            <div className="bg-white p-2 rounded-lg shadow-sm">
                <QRCode 
                    id="qr-code-svg"
                    value={product.id} 
                    size={160}
                    level="H"
                />
            </div>
            <p className="font-mono font-bold mt-4 text-slate-600">{product.id}</p>
        </div>

        <div className="mt-6">
            <button onClick={handlePrint} className="w-full bg-qq-green hover:bg-qq-green-dark text-white py-3.5 rounded-xl font-bold flex items-center justify-center gap-2 shadow-lg shadow-qq-green/20 transition-all active:scale-95">
                <Printer size={20} />
                Imprimir
            </button>
        </div>
      </div>
    </div>
  );
};

export default QRModal;