import React from 'react';
import QRCode from 'react-qr-code';
import { Printer } from 'lucide-react';
import { Product } from '../../types';
import ActionModal from '../ui/ActionModal';

interface QRModalProps {
  product: Product;
  onClose: () => void;
}

const QRModal: React.FC<QRModalProps> = ({ product, onClose }) => {
  const handlePrint = () => {
    const printWindow = window.open('', '', 'height=500,width=500');
    if (printWindow) {
        // We get the SVG generated by the library
        const svg = document.getElementById("qr-code-svg")?.outerHTML || "";
        
        printWindow.document.write(`
            <html>
                <body style="display:flex; flex-direction:column; align-items:center; justify-content:center; height:100%; font-family:sans-serif;">
                    <h2 style="margin-bottom:10px;">${product.name}</h2>
                    ${svg}
                    <p style="margin-top:10px; font-weight:bold; font-family:monospace;">${product.id}</p>
                    <script>
                        setTimeout(() => { window.print(); window.close(); }, 500);
                    </script>
                </body>
            </html>
        `);
        printWindow.document.close();
    }
  };

  return (
    <ActionModal
      title="Etiqueta"
      subtitle={product.name + ' - SKU ' + product.id}
      onClose={onClose}
      maxWidthClass="max-w-md"
      footer={
        <button onClick={handlePrint} className="w-full bg-qq-green hover:bg-qq-green-dark text-white py-3.5 rounded-xl font-bold flex items-center justify-center gap-2 shadow-lg shadow-qq-green/20 transition-all active:scale-95">
          <Printer size={20} />
          Imprimir
        </button>
      }
    >
        <div className="bg-slate-50 border-2 border-dashed border-slate-200 rounded-xl p-6 flex flex-col items-center">
            <h4 className="font-bold text-lg mb-4 text-center break-words">{product.name}</h4>
            <div className="bg-white p-2 rounded-lg shadow-sm">
                <QRCode 
                    id="qr-code-svg"
                    value={product.id} 
                    size={160}
                    level="H"
                />
            </div>
            <p className="font-mono font-bold mt-4 text-slate-600">{product.id}</p>
        </div>
    </ActionModal>
  );
};

export default QRModal;
